[build]
  base = "."
  publish = "public/"
  command = "hugo --gc --minify --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  TZ = "Europe/Paris"
  